### ISSUE TITLE
Text conversion: Three characters get a trailing . for free

### ISSUE THREAD

**Issue by manavortex** [jhunt/hex-alfred#1]
I try it by running hex was and end up with 
![Alt text](https://monosnap.com/file/haOOuLBpzIab9h97Fgpmxll8CyaLkN.png)

Works fine otherwise! I'd fix it myself if not for the fact that the file was compiled already. :)

**Comment by jhunt** [comment]
The `.` signifies an unprintable character in the 8-bit ASCII alphabet.  Since we zero-pad to 4 octets, and then left-fill, the last octet is `0x00`, which is not printable (ASCII NUL has no glyph).

**Comment by manavortex** [comment]
Ah, I see. 
I don't suppose you could cut them off from the displayed result though?

**Comment by jhunt** [comment]
Doing so adds complexity, and it would raise similar issues for some other formats.  What does decimal 16 mean when you only have 3 octets and aren't zero-padding?

**Comment by manavortex** [comment]
True - I'm using it to encrypt passwords mainly. I've added another script that cuts off the additional zeroes from the clipboard result, it's only perfectionism.

**Comment by jhunt** [comment]
Interesting.  I've never used it for anything other than inspecting the results.  Kind of like a mini-hex editor in Alfred.  If you don't mind my asking, how are you encrypting them?

**Comment by manavortex** [comment]
I add "random" numbers to my passwords by throwing every n-th character from the URL into a generator. That way I can still recover my passwords later if I forget them.

**Comment by jhunt** [comment]
Have you considered a password manager?  I use 1password and it's quite nice.

**Comment by manavortex** [comment]
Both. Better safe than sorry! :)
